### ISSUE TITLE
differ

### ISSUE THREAD

**Issue by mitrasero** [openbridge/ob_cloak#1]
hi 
in what way does this differ from onetime secret ? is it simply a docker image ?

**Comment by tspicer** [comment]
@mitrasero  docker, docker-entry, environment variables for run-time, updated gem packages, optimizations for use with Alpine Linux,  different creative (cloak.sh), processing monitor (monit), thin config, configurable creative (default OTS), compose....

basically, "simply" a docker image actually entails refactoring how the application is packaged, initialized and operated. Of course, you could attempt to just wrap it with Docker but I doubt you would get very far.

**Comment by mitrasero** [comment]
Hi 
Thank you for the effort !
